export const resources = {
  usuarios: { label:'Usuarios', singular:'usuario', endpoint:'/usuarios/', columns:['id','nombre','apellido','correo','idrol','estado'], search:['nombre','apellido','correo'], fields:[
    {name:'nombre',label:'Nombre',required:true,max:100},{name:'apellido',label:'Apellido',required:true,max:100},{name:'correo',label:'Correo electrónico',type:'email',required:true,max:150},{name:'password',label:'Contraseña',type:'password',required:true,min:10,max:255,createOnly:true},{name:'idrol',label:'Rol',type:'relation',relation:'rol',required:true},{name:'estado',label:'Estado',type:'boolean',default:true}
  ]},
  rol: { label:'Roles', singular:'rol', endpoint:'/roles/', columns:['id','nombre','descripcion','estado'], search:['nombre','descripcion'], fields:[{name:'nombre',label:'Nombre',required:true,max:50},{name:'descripcion',label:'Descripción',type:'textarea',max:255},{name:'estado',label:'Estado',type:'boolean',default:true}]},
  modulo: { label:'Módulos', singular:'módulo', endpoint:'/modulos/', columns:['id','nombre','ruta','icono','estado'], search:['nombre','descripcion','ruta'], fields:[{name:'nombre',label:'Nombre',required:true,max:100},{name:'descripcion',label:'Descripción',type:'textarea',max:255},{name:'ruta',label:'Ruta',max:255},{name:'icono',label:'Icono',max:100},{name:'estado',label:'Estado',type:'boolean',default:true}]},
  modulo_x_rol: { label:'Permisos por rol', singular:'permiso', endpoint:'/modulo-x-rol/', columns:['id','idrol','idmodulo','estado'], search:['idrol','idmodulo'], fields:[{name:'idrol',label:'Rol',type:'relation',relation:'rol',required:true},{name:'idmodulo',label:'Módulo',type:'relation',relation:'modulo',required:true},{name:'estado',label:'Activo',type:'boolean',default:true}]},
  tipo_sensor: { label:'Tipos de sensor', singular:'tipo de sensor', endpoint:'/tipos-sensor/', columns:['id','nombre','unidad_medida','fabricante','modelo','estado'], search:['nombre','fabricante','modelo'], fields:[{name:'nombre',label:'Nombre',required:true,max:50},{name:'descripcion',label:'Descripción',type:'textarea',max:255},{name:'unidad_medida',label:'Unidad de medida',required:true,max:20},{name:'fabricante',label:'Fabricante',max:100},{name:'modelo',label:'Modelo',max:100},{name:'estado',label:'Estado',type:'boolean',default:true}]},
  sensor: { label:'Sensores', singular:'sensor', endpoint:'/sensores/', columns:['id','codigo','nombre','idtiposensor','modelo','ubicacion_fisica','estado','fecha_instalacion'], search:['codigo','nombre','fabricante'], fields:[{name:'idtiposensor',label:'Tipo de sensor',type:'relation',relation:'tipo_sensor',required:true},{name:'codigo',label:'Código',required:true,max:50},{name:'nombre',label:'Nombre',required:true,max:100},{name:'modelo',label:'Modelo',max:100},{name:'fabricante',label:'Fabricante',max:100},{name:'ubicacion_fisica',label:'Ubicación física',max:255},{name:'estado',label:'Activo',type:'boolean',default:true},{name:'fecha_instalacion',label:'Fecha de instalación',type:'datetime'}]},
  dpto: { label:'Departamentos', singular:'departamento', endpoint:'/dptos/', columns:['id','nombre','codigo','estado'], search:['nombre','codigo'], fields:[{name:'nombre',label:'Nombre',required:true,max:100},{name:'codigo',label:'Código',max:10},{name:'estado',label:'Activo',type:'boolean',default:true}]},
  locacion: { label:'Locaciones', singular:'locación', endpoint:'/locaciones/', columns:['id','nombre','iddpto','direccion','latitud','longitud','estado'], search:['nombre','direccion','descripcion'], fields:[{name:'iddpto',label:'Departamento',type:'relation',relation:'dpto',required:true},{name:'nombre',label:'Nombre',required:true,max:100},{name:'descripcion',label:'Descripción',type:'textarea',max:255},{name:'direccion',label:'Dirección',max:255},{name:'latitud',label:'Latitud',type:'number',min:-90,max:90,step:'0.000001'},{name:'longitud',label:'Longitud',type:'number',min:-180,max:180,step:'0.000001'},{name:'estado',label:'Activa',type:'boolean',default:true}]},
  asignacion_sensor: { label:'Asignaciones', singular:'asignación', endpoint:'/asignaciones-sensor/', columns:['id','idusuario','idsensor','fecha_asignacion','fecha_fin','estado'], search:['estado','idusuario','idsensor'], fields:[{name:'idusuario',label:'Usuario',type:'relation',relation:'usuarios',required:true},{name:'idsensor',label:'Sensor',type:'relation',relation:'sensor',required:true},{name:'fecha_asignacion',label:'Fecha de asignación',type:'datetime'},{name:'fecha_fin',label:'Fecha de finalización',type:'datetime'},{name:'estado',label:'Estado',type:'select',options:['ACTIVA','FINALIZADA'],default:'ACTIVA',required:true}]},
  lectura: { label:'Lecturas', singular:'lectura', endpoint:'/lecturas/', columns:['id','idsensor','idlocacion','valor','temperatura','fecha_hora','calidad'], search:['valor','calidad','idsensor'], fields:[{name:'idsensor',label:'Sensor',type:'relation',relation:'sensor',required:true},{name:'idlocacion',label:'Locación',type:'relation',relation:'locacion',required:true},{name:'valor',label:'pH',type:'number',required:true,min:0,max:14,step:'0.01'},{name:'temperatura',label:'Temperatura °C',type:'number',min:-999.99,max:999.99,step:'0.01'},{name:'fecha_hora',label:'Fecha y hora',type:'datetime'},{name:'calidad',label:'Calidad',max:50}]
  }
};

export const labels = { id:'ID',nombre:'Nombre',apellido:'Apellido',correo:'Correo',password:'Contraseña',idrol:'Rol',estado:'Estado',descripcion:'Descripción',ruta:'Ruta',icono:'Icono',idmodulo:'Módulo',unidad_medida:'Unidad',fabricante:'Fabricante',modelo:'Modelo',idtiposensor:'Tipo de sensor',codigo:'Código',ubicacion_fisica:'Ubicación física',fecha_instalacion:'Instalación',iddpto:'Departamento',direccion:'Dirección',latitud:'Latitud',longitud:'Longitud',idsensor:'Sensor',idlocacion:'Locación',valor:'pH',temperatura:'Temperatura',fecha_hora:'Fecha y hora',calidad:'Calidad',idusuario:'Usuario',fecha_asignacion:'Asignado el',fecha_fin:'Fecha fin' };
export const relationResources = { rol:'rol', modulo:'modulo', tipo_sensor:'tipo_sensor', sensor:'sensor', dpto:'dpto', locacion:'locacion', usuarios:'usuarios' };
